### ISSUE TITLE
Add use cases

### ISSUE THREAD

**Issue by paragasu** [phisoft/kertasdms-web#20]
pick a few industry & explain how kertasdms will help

**Comment by Suzitaothman** [comment]
## Order in Court
Working in court, lawyers and judges, I believe deal with tons of paper for every case they were assigned. With the KertasDM system it's more convenient for them in form of e-paper instead of carrying around a luggage of documents.
1. Just by scanning the hardcopy of documents, you won't have to worry if the hardcopy goes missing.
2. If other colleagues ask for a copy, you can just simply update the document in the system.
3. Most importantly, the 'search' features in KertasDMs. You don't have to go through each document, just simply scan the qr code tools.
